### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by ncallister** [ascom-au/asterisk-role#1]
Release the first version of this role following the release procedure here: http://192.168.1.5/iwsoftware/wiki/Processes/Release/AnsibleRoles

- [x] Ensure that there is an issue for the release in the release milestone in order to track any changes required
- [x] Ensure that all issues assigned to the release milestone have been closed (except for the release issue)
- [x] Ensure that all issues that have resulted in commits have been closed (you will need to dig through the commit messages because many of the issues will belong to playbook projects)
- [x] Ensure that all issue specific branches have been merged and removed 

- [x] Create a tag for the release version
- [ ] Close the release issue
- [x] Close the milestone
- [x] Create a milestone for the next release by creating the issue to release the next version

**Comment by amidha** [comment]
Checked that all the above tickets are closed.

**Comment by amidha** [comment]
Branch ensurespeech-issue#9 has been merged already. https://github.com/ascom-au/ensurespeech-playbook/commit/2f5c63f98658501314ce666278e43045d895258b

Deleted the branch ensurespeech-issue#9

**Comment by amidha** [comment]
Created tag release_1.0 https://github.com/ascom-au/asterisk-role/tags

**Comment by amidha** [comment]
Closed the milestone. Created a new release ticket and assigned it next milestone.

**Comment by serg89** [comment]
## Review

The work performed for this release so far is fine, however there is a few items still to be completed:

1. Create v1.0.1 milestone for bug fix releases (v1.1 is for feature releases)
2. Create release issue for v1.0.1 milestone.
3. Create branch_1.0 for new development work.

Please see the work done in the other roles (e.g. java role) for a guide.

**Comment by ncallister** [comment]
A new issue has been created to release version 1.0.1: #4

**Comment by serg89** [comment]
## Review 2

1. Milestone v1.0.1 created? https://github.com/ascom-au/asterisk-role/milestones/1.0.1 created.
2. Release issue for v1.0.1 milestone? https://github.com/ascom-au/asterisk-role/issues/4 created.
3. branch_1.0 created for new development work? https://github.com/ascom-au/asterisk-role/tree/branch_1.0 created.

Review completed. Ready for QA.

**Comment by serg89** [comment]
Closing this ticket since v1.0.1 was meant for future work but due to existing bugs was started soon after this ticket and has already been released (https://github.com/ascom-au/asterisk-role/milestones/1.0.2 has already been created) so QA is moot at this point for v1.0!
